name: Build & Deploy

# Trigger on push to your chosen branch
on:
  push:
    branches:
      - eleventy-migration   # or 'main'

jobs:
  build-and-deploy:
    name: Build Eleventy and Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'    # matches your local version

      - name: Install dependencies
        run: npm ci

      - name: Build Eleventy site
        run: npm run build    # this runs 'eleventy' by your script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site         # Eleventy output folder
          # If you want to publish from a separate branch:
          # publish_branch: gh-pages

