name: Build Eleventy and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write    # allow pushing to gh-pages
  pages:    write    # allow updating GitHub Pages
  id-token: write    # required by some Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0               # <<-- important for gh-pages to work properly

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build CSS & Eleventy
        run: npm run build            # assumes your "build" script runs both CSS and Eleventy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages   # <<-- ensures it updates gh-pages
          publish_dir:    ./_site     # your Eleventy output
